language: r
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      env: R_CODECOV=true
#    - os: osx
#      osx_image: xcode8.3
#      latex: false

r_packages:
  - covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then ./scripts/codecov.R; fi
